---
- name: 'Send kafka-lag-exporter configs'
  template:
    src: 'templates/{{ item }}.j2'
    dest: '/opt/kafka-lag-exporter/conf/{{ item }}'
    owner: kafka
    group: kafka
    mode: 0644
  loop:
    - kafka-lag-exporter.conf
    - logback.xml

- name: 'Sending systemd-files'
  template:
    src: 'templates/kafka-lag-exporter.service.j2'
    dest: '/etc/systemd/system/kafka-lag-exporter.service'
    owner: kafka
    group: kafka
    mode: 0644

- name: 'Daemon reload'
  systemd:
    daemon_reload: yes
