---
- name: Download kafka-lag-exporter archive
  get_url:
    url: 'https://github.com/lightbend/kafka-lag-exporter/releases/download/v0.8.2/kafka-lag-exporter-0.8.2.zip'
    dest: '/tmp/kafka-lag-exporter-0.8.2.zip'

- name: Unarchive kafka-lag-exporter
  unarchive:
    src: '/tmp/kafka-lag-exporter-0.8.2.zip'
    dest: '/opt/'
    remote_src: yes

- name: Set ownership and permissions
  file:
    path: '/opt/kafka-lag-exporter-0.8.2'
    owner: kafka
    group: kafka
    mode: '0755'
    state: directory

- name: Rename kafka-lag-exporter directory if necessary
  command: 'mv /opt/kafka-lag-exporter-{{ kafka_lag_exporter_version }} /opt/kafka-lag-exporter'
  args:
    creates: '/opt/kafka-lag-exporter'




- name: 'Create conf dir'
  file:
    state: directory
    path: /opt/kafka-lag-exporter/conf
    owner: kafka
    group: kafka
    mode: 0755

- name: 'Chown dir'
  command: 'chown -R kafka:kafka /opt/kafka-lag-exporter'

- name: 'Send kafka-lag-exporter configs'
  template:
    src: 'templates/{{ item }}.j2'
    dest: '/opt/kafka-lag-exporter/conf/{{ item }}'
    owner: kafka
    group: kafka
    mode: 0755
  loop:
    - kafka-lag-exporter.conf
    - logback.xml

- name: 'Sending systemd-files'
  template:
    src: 'templates/kafka-lag-exporter.service.j2'
    dest: '/etc/systemd/system/kafka-lag-exporter.service'
    owner: kafka
    group: kafka
    mode: 0755

- name: 'Daemon reload'
  systemd:
    daemon_reload: yes

- name: Start Kafka Lag Exporter service
  systemd:
    name: kafka-lag-exporter
    state: restarted