---
- name: 'Sending systemd-files'
  template:
    src: 'templates/kafka.service.j2'
    dest: '/etc/systemd/system/kafka.service'
    owner: kafka
    group: kafka
    mode: 0644
    backup: yes 

- name: 'Daemon reload'
  systemd:
    daemon_reload: yes

- name: Start Kafka service
  systemd:
    name: kafka
    state: restarted
